version: '3.5'

services:
  postgres:
    image: postgres:17.2-alpine3.21
    container_name: 'db'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: bd
    volumes:
      - /var/lib/postgresql/data
